
services:
  mongodb:
    image: mongo:6.0
    container_name: mongodb
    ports:
      - "27117:27017"
    volumes:
      - mongodata:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    networks:
      - backend
    restart: always

networks:
  backend:

volumes:
  mongodata:
